parameters:
#    syrup_aws.example.class: Syrup\AwsBundle\Example

services:
#    syrup_aws.example:
#        class: %syrup_aws.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
