parameters:
#    syrup_extractor.example.class: Syrup\ExtractorBundle\Example

services:
    syrup.extractorbundle.listener.exception:
        class: Syrup\ExtractorBundle\Listener\SyrupExceptionListener
        arguments: [@logger]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    syrup.extractorbundle.listener.controller:
        class: Syrup\ExtractorBundle\Listener\SyrupControllerListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    syrup.extractor_factory:
        class: Syrup\ExtractorBundle\Extractor\ExtractorFactory
        arguments: [@logger]
    syrup.monolog.json_formatter:
        class: Syrup\ExtractorBundle\Monolog\Formatter\SyrupJsonFormatter
        arguments: [%app_name%]
