imports:
    - { resource: config.yml }

monolog:
    handlers:
        syslog:
            ident: %app_name%
            type: syslog
            level: info
            formatter: syrup.monolog.json_formatter
