parameters:
    locale: en
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    pdo.db_options:
        db_table: sessions
        db_id_col: id
        db_data_col: value
        db_time_col: time