syrup_index:
    path:      /
    defaults:  { _controller: SyrupBundle:Index:index }

syrup_core:
    resource: .
    type: component

syrup_component:
    resource: "@SyrupBundle/Resources/config/routing.yml"
    prefix:   /