services:
    pdo:
        class: PDO
        arguments:
            - "mysql:host=%syrup.host%;dbname=%syrup.name%"
            - "%syrup.user%"
            - "%syrup.password%"
        calls:
            - [setAttribute, [3,2]] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION

    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments: [@pdo, %pdo.db_options%]