parameters:
#    syrup_slevomat.example.class: Syrup\SlevomatBundle\Example

services:
#    syrup_slevomat.example:
#        class: %syrup_slevomat.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
